#!/usr/bin/env bash
# Stop the 4-to_infinity_and_beyond process using kill
# shellcheck disable=SC2009

# Get PIDs of the process
pids=$(pgrep -f 4-to_infinity_and_beyond)

# If any PID found, kill them
if [[ -n "$pids" ]]; then
    kill $pids
fi

# Confirm
echo "process killed"
