#!/usr/bin/env bash
# Display "To infinity and beyond indefinitely" with sleep 2
# Print "I am invincible!!!" when receiving SIGTERM

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
    echo "To infinity and beyond indefinitely"
    sleep 2
done
